node('Built-In Node') {
    docker.image('python:2-alpine').inside('-p 3000:3000') {
        stage('Build') {
            checkout scm
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }
    docker.image('qnib/pytest').inside('-p 3000:3000') {
        stage('Test') {
            checkout scm
            sh 'py.test --junit-xml test-reports/results.xml sources/test_calc.py'
            junit 'test-reports/results.xml'
        }
    }
}
    node('ec2-agent') {
        docker.image('cdrx/pyinstaller-linux:python2').inside{
            def VOLUME = "${pwd()}/sources:/src"
            def BUILD_ID = env.BUILD_ID
            def IMAGE = IMAGE_PYINSTALLER
            stage('Deploy') {
                unstash('compiled-results')
                sh "docker run --rm -v ${VOLUME} ${IMAGE} 'pyinstaller -F add2vals.py'"
            }
            stage('Post-Deploy') {
                sh "docker run --rm -v ${VOLUME} ${IMAGE} 'rm -rf build dist'"
                archiveArtifacts "${BUILD_ID}/sources/dist/add2vals"
            }
        }
    }

